
version: '2'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    network_mode: bridge
    container_name: api-container
    environment:
      - VIRTUAL_HOST=api.originapi.com
      - NODE_ENV=production
      - PROD=true
    ports:
      - "3000:3000"
    command: "npm run start"
  postgraphile:
    build:
      context: ./graphql
      dockerfile: Dockerfile.graphql
    network_mode: bridge
    container_name: graphql-container
    environment:
      - VIRTUAL_HOST=dev.graphql.originapi.com
      - NODE_ENV=development
      - PROD=true
    ports:
      - "5001:5001"
    command: "npm run start"
  postgraphile_prod:
    build:
      context: ./graphql
      dockerfile: Dockerfile.graphql
    network_mode: bridge
    container_name: graphql-prod-container
    environment:
      - VIRTUAL_HOST=graphql.originapi.com
      - NODE_ENV=production
      - PROD=true
    ports:
      - "5000:5000"
    command: "npm run start"  
  nginx:
    build:
      context: ./graphql
      dockerfile: Dockerfile.nginx
    network_mode: bridge
    container_name: nginx-container
    environment:
      - VIRTUAL_HOST=www.origin.gg,origin.gg,*.origin.gg
      - NODE_ENV=production
      - PROD=true
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/build:/wwwroot
  nginx-proxy:
    image: jwilder/nginx-proxy
    network_mode: bridge
    container_name: nginx-proxy-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/applications/graphql/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
      - ~/applications/backend_server/certs:/etc/nginx/certs


