version: "3"


services:
  postgraphql:
    build: ./dockerfiles
    container_name: postgraphql
    image: erasche/postgraphql:latest
    ports:
        - "5000:5000"
    expose:
        - "5000"
    environment:
        #DB_DEFAULT_ROLE: postgres
        DB_GRAPHIQL_PATH: "/graphiql"
        DB_SCHEMA: "origin"
        PGUSER: origin_postgraphql
        PGPASSWORD: allegro1234
        PGHOST: origingg.cjdraitfnk0j.us-east-1.rds.amazonaws.com
        PGDATABASE: originGG
        PGJWTSECRET: udsxlF711HCTcrl4hRLgsH1PIcbidZmqy7urJGef0aMRPzrWoTjAV9DOHt1rZao2
        PGTOKEN: origin.jwt_token
        PGDEFAULTROLE: origin_anonymous
        PGPORT: 5432
        GQL_PORT: 5000
