FROM node:8.10.0
  RUN apt-get update
  WORKDIR /usr/src/app
  RUN npm install -g pm2@latest
  RUN pm2 install pm2-logrotate
  RUN pm2 set pm2-logrotate:retain 1
  COPY ./package.json /usr/src/app/package.json
  COPY ./ /usr/src/app
  COPY ./.env.production /usr/src/app/.env
  RUN npm install